### ISSUE TITLE
When shift-pressing a topsy key, the key is heavily repeated.

### ISSUE THREAD

**Issue by Soares** [keyboardio/Kaleidoscope-TopsyTurvy#7]
When I run the Topsy Turvy plugin example (https://github.com/keyboardio/Kaleidoscope-TopsyTurvy/blob/master/examples/TopsyTurvy/TopsyTurvy.ino), it successfully makes it so that pressing 1 (unshifted) types “!” and so on, but unfortunately, when I press 1 while shifted, it types something like “11111111111111111111” instead of “1”. Same with all the other numbers – their unshifted versions type a symbol, as expected, but their shifted versions type the unshifted number a couple dozen times.

See also: https://community.keyboard.io/t/trouble-with-topsyturvy/903
Possibly also related to https://github.com/keyboardio/Kaleidoscope-TopsyTurvy/issues/6

**Comment by algernon** [comment]
It's the same as #6. I have an idea or two to fix it, will hopefully get around to it this week. Closing this as a duplicate, so that I don't get scared by the amount of open issues against Kaleidoscope plugins O:)
