### ISSUE TITLE
Possibility to change normal key to altgr (RightAlt) instead on normal to shift key.

### ISSUE THREAD

**Issue by alexandrenavarro** [keyboardio/Kaleidoscope-TopsyTurvy#9]
Possibility to change normal key to altgr (RightAlt) instead on normal to shift key.
It can be useful for instance on some keymap like bépo (something like dvorak but for french) where some keys are direct like «» instead of <> on altgr which are useful in programming for instance.
I check quickly the code, it seems not very hard to change it to manage in addition that but what kind of solution?
Every in the current plugin with new function? New plugin forked? Another solution?
Tell me what you preffered, I'm not a C++ programmer (java/kotlin) but I can try to do something if you want when I will have time.

**Comment by gedankenexperimenter** [comment]
Without any plugins, it is already possible to map a key to `AltGr` + `X` (for any `X`). Would that solve the problem?

**Comment by alexandrenavarro** [comment]
My point is not just to associate a key X to equivalent of altGr + X , but also associate altGr + X  to previous X. In deed, I want to inverse the altgr and normal key. I have also one usecase to inverse shift and altgr key. If I understand well, TopsyTurvy plugin can do it but only between normal and shift key.

**Comment by alexandrenavarro** [comment]
Yes to your question. Thank you for your answer, I did not know (or realize) that only keycodes (not characters) are sent by the keyboard. I thought managing the change will be better in the keyboard (I used 3 computers but on Linux and Windows) but definitely it is not a good choice, create a custom keymap by os seems to be a better choice. Thanks again.
